version: '3.9'

services:
  meteorit_bot:
    build: .
    container_name: meteorit_bot
    restart: always
    volumes:
      - ./bookings.db:/app/bot/bookings.db
    env_file:
      - .env
    networks:
      - tg-bots

networks:
  tg-bots:
    external: true
